class_path: chebai_graph.models.graph.ResGatedGraphConvNetGraphPred
init_args:
  optimizer_kwargs:
    lr: 1e-3
  config:
    in_length: 256
    hidden_length: 512
    dropout_rate: 0.1
    n_conv_layers: 3
    n_linear_layers: 3
    n_atom_properties: 158
    n_bond_properties: 7
    n_molecule_properties: 200
