class_path: chebai_graph.models.gin_net.GINEConvNet
init_args:
  optimizer_kwargs:
    lr: 0.0001
  config:
    hidden_size: 512
    dropout_rate: 0.2
    n_conv_layers: 6
    n_linear_layers: 4
    n_atom_properties: 125
    n_bond_properties: 5