class_path: chebai_graph.models.ResGatedAugNodePoolGraphPred
init_args:
  optimizer_kwargs:
    lr: 1e-3
  config:
    in_channels: 203 # number of node/atom properties
    hidden_channels: 256
    out_channels: 512
    num_layers: 4
    edge_dim: 12 # number of bond properties
    dropout: 0
  n_molecule_properties: 0
  n_linear_layers: 1
