class_path: chebai_graph.models.ResGatedGraphPred
init_args:
  optimizer_kwargs:
    lr: 1e-3
  config:
    n_node_properties: 68 # in_channels
    hidden_channels : 256
    out_channels : 512
    num_layers : 4
    n_bond_properties: 4 # edge_dim
  n_molecule_properties: 0
  n_linear_layers: 2
